version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "443:8443"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/librored
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=-zFp2.MaFn2@L4Tv
    restart: on-failure

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=-zFp2.MaFn2@L4Tv
      - MYSQL_DATABASE=librored
    ports:
      - "3306:3306"
