@startuml
left to right direction
skinparam packageStyle rectangle
title Class Diagram
package "Repository" {
  class LoanRepository
  class BookRepository
  class UserRepository
}
package "DTO" {
  class BookDTO
  class BookUpdateDTO
  class LoanCreateDTO
  class UserUpdateDTO
  class LoanUpdateDTO
  class UserCreateDTO
  class LoanDTO
  class UserDTO
  class BookCreateDTO
  class OpenLibraryAuthorSearchResponseDTO
}
package "Security" {
  class SecurityConfig
  class UserDetailsImpl
  class CSRFHandlerConfiguration
}
package "jwt"{
  class AuthRequest
  class AuthRequestController
  class AuthService
  class JwtAuthFilter
  class JwtProvider
  class JwtRequestFilter
  class JwtUtil
  class UnauthorizedHandlerJwt
  class UserDetailsImpl
}
package "Service" {
  class RepositoryUserDetailsService
  class AuthService
  class UserService
  class LoanService
  class ExternalAuthorService
  class UserDetailsServiceImpl
  class DatabaseInitializer
  class BookService
}
package "RestController" {
  class AuthRestController
  class UserRestController
  class LoanRestController
  class ExternalAuthorRestController
  class BookRestController
}
package "Mapper" {
  class LoanMapper
  class UserMapper
  class BookMapper
  class LoanMapper
  class UserMapper
  class BookMapper
}
package "Controller" {
  class CustomErrorController
  class GlobalModelAttributes
  class PostLoginController
  class BookController
  class LoginWebController
  class UserController
}
package "Model" {
  class User
  class Loan
  class Book
}

Controller --> Service
RestController --> Service
Service --> Repository
Repository --> Model
Service --> Mapper
RestController --> DTO
Service --> Security
Security --> jwt
jwt --> Service

@enduml